
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.edd_practica_2.parser_img;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR = 7;
  public static final int BRACE_RIGHT = 3;
  public static final int error = 1;
  public static final int NUMBER = 5;
  public static final int SEMI = 6;
  public static final int COLON = 4;
  public static final int BRACE_LEFT = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BRACE_LEFT",
  "BRACE_RIGHT",
  "COLON",
  "NUMBER",
  "SEMI",
  "COLOR"
  };
}

