/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.edd_practica_2.ui;

import com.mycompany.edd_practica_2.matriz_dispersa.Capa;
import static com.mycompany.edd_practica_2.ui.Frame.paneRoot;
import java.io.File;
import javax.swing.JOptionPane;
import prueba.Nodo;

/**
 *
 * @author Temporal
 */
public class CapaUI extends javax.swing.JPanel {

    /**
     * Creates new form CapaUI
     */
    public CapaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdCapa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jButton1.setText("ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(txtIdCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txtIdCapa.getText().isEmpty()) {
            int id = Integer.parseInt(txtIdCapa.getText());
            Nodo<Capa<String>> nodoCapa = Frame.capas.buscar(new Capa<String>(id), Frame.capas.getRoot());
            
            nodoCapa.getValue().graph("Capa-"+txtIdCapa.getText()+".dot", "Capa-"+txtIdCapa.getText()+".png");
            loadImage("Capa-"+txtIdCapa.getText()+".png");
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void loadImage(String path) {
        File file = new File(path);
        if (file.exists()) {
            LoadImage imagen = new LoadImage(file.getAbsolutePath());
            imagen.setSize(paneRoot.getWidth(), paneRoot.getWidth());
            paneRoot.removeAll();
            paneRoot.add(imagen);
            paneRoot.repaint();
        }else{
            JOptionPane.showMessageDialog(null, "Error Al Cargar la Imagen","Informacion",JOptionPane.ERROR_MESSAGE);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtIdCapa;
    // End of variables declaration//GEN-END:variables
}
